apiVersion: v1
kind: Secret
metadata:
  name: feast-data-stores
  namespace: feast
stringData:
  redis: |
    connection_string: redis.feast.svc.cluster.local:6379
  sql: |
    path: postgresql+psycopg://feast:feast@postgres.feast.svc.cluster.local:5432/feast
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
        echo: false
        pool_pre_ping: true
---
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: sample
  namespace: feast
spec:
  feastProject: my_project
  feastProjectDir:
    git:
      configs:
        'url."https://api:token@github.com/".insteadOf': 'https://github.com/'
      url: 'https://github.com/kromeo6/tmptestrepo.git'
  services:
    # offlineStore:
    #   server: {}
    # registry:
    #   local:
    #     server: {}
    onlineStore:
      persistence:
        store:
          type: redis
          secretRef:
            name: feast-data-stores
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores
    ui: {}


# apiVersion: feast.dev/v1alpha1
# kind: FeatureStore
# metadata:
#   name: sample
# spec:
#   feastProject: my_project
