
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../manifests/common/cert-manager/kubeflow-issuer/base

patches:
  - target:
      kind: ClusterIssuer
      name: kubeflow-self-signing-issuer
    patch: |-
      - op: remove
        path: /metadata/namespace