name: w1 workflow prod
on: push


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World!"
    - name: Print status
      run: echo "Workflow status: ${{ job.status }}"
