name: w1 workflow
on: push


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          submodules: true

    - name: Print Hello World
      run: echo "Hello, World! from w1"

    - name: List submodule directory
      run: |
        echo "Listing contents of the submodule directory:"
        ls -la my-testtrit
