name: w2 prod
on:
  workflow_run:
    workflows: ["w1 workflow"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Hello World w2
      run: echo "Hello, World from hw2!"

    - name: Print Current Branch
      run: echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
